### PR TITLE
Issue #47 (ST-1931, ST-1935): Fix typo and wrong path

### PR DESCRIPTION
**Pull request by zyfdegh**

### CODE REVIEW

**Comment by kkdai** [comment]
Can one of the admins verify this patch?

**Comment by kkdai** [comment]
Can one of the admins verify this patch?

**Comment by kkdai** [comment]
Since PR-1027 already include, please help to update binary and this PR

**Comment by zyfdegh** [comment]
@kkdai thank u for reminding. updated

**Pull request merged**
