### PR TITLE
ST-1931, ST-1935: Rename submit tool

### PR DESCRIPTION
**Pull request by zyfdegh**
- add build arg SUBMIT_TOOL_NAME for trainer images

### CODE REVIEW

**Comment by kkdai** [comment]
Can one of the admins verify this patch?

**Comment by kkdai** [comment]
Can one of the admins verify this patch?

**Comment by zyfdegh** [comment]
In Jenkins, we'll set SUBMIT_TOOL_NAME to `aiforge` if the branch is `rc`

**Comment by zyfdegh** [comment]
reopen

**Comment by kkdai** [comment]
Can one of the admins verify this patch?

**Comment by kkdai** [comment]
Can one of the admins verify this patch?

**Comment by zyfdegh** [comment]
Jenkins configurations updated

**Pull request merged**
